apiVersion: v1
kind: Pod
metadata:
  name: part2-app
  labels:
    app.kubernetes.io/name: part2-app
    app.kubernetes.io/component: frontend
spec:
  containers:
  - image: mmumshad/simple-webapp-color
    env:
    - name: APP_COLOR
      value: "blue"
    name: part2-app
    ports:
    - containerPort: 8080
      protocol: TCP