apiVersion: v1
kind: Pod
metadata:
  name: part2-app-with-configmap
  labels:
    app.kubernetes.io/name: part2-app-with-configmap
    app.kubernetes.io/component: frontend
spec:
  containers:
  - image: mmumshad/simple-webapp-color
    env:
    - name: APP_COLOR
      valueFrom: 
        configMapKeyRef:
          name: config-part2-app
          key: APP_COLOR
    name: part2-app-with-configmap
    ports:
    - containerPort: 8080
      protocol: TCP