apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-guestbook
  labels:
    app.kubernetes.io/name: php-guestbook
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: php-guestbook
      app.kubernetes.io/component: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: php-guestbook
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: php-guestbook
        image: paulczar/gb-frontend:v5
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80