apiVersion: v1
kind: Service
metadata:
  name: php-guestbook
  labels:
    app.kubernetes.io/name: php-guestbook
    app.kubernetes.io/component: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app.kubernetes.io/name: php-guestbook
    app.kubernetes.io/component: frontend